# Generated by Django 5.0.4 on 2024-04-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Music",
            new_name="Song",
        ),
        migrations.RemoveField(
            model_name="team",
            name="artist",
        ),
        migrations.AddField(
            model_name="team",
            name="songs",
            field=models.ManyToManyField(related_name="played_by", to="core.song"),
        ),
    ]
