# Generated by Django 5.0.4 on 2024-04-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_team_others"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="link"),
        ),
    ]
