# Generated by Django 5.0.4 on 2024-04-19 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_song_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="concert",
            name="teams",
        ),
        migrations.CreateModel(
            name="Collaboration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.song"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.team"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="concert",
            name="collaborations",
            field=models.ManyToManyField(
                related_name="concerts", to="core.collaboration"
            ),
        ),
    ]
